trigger:
- main
- dev

pool:
  demands:
  - Agent.Name -equals Nombre-De-Mi-Agente

steps:
- task: AzureCLI@2 
  displayName: 'Desplegar DB usando un pipeline'
  inputs:
    azureSubscription: 'nombre-del-service-conection' 
    scriptType: ps 
    scriptLocation: inlineScript 
    inlineScript: |  
      $RESOURCE_GROUP = "nombre-del-grupo-de-recursos"
      $LOCATION = "centralus"
      $SQL_SERVER_NAME = "nombre-del-servidor-sql"
      $ADMIN_USER = "usuario-admin"
      $ADMIN_PASSWORD = "clave-segura"
      $DATABASE_NAME = "myDatabase"

      Write-Output "Creando el grupo de recursos..."
      az group create --name $RESOURCE_GROUP --location $LOCATION

      Write-Output "Creando el servidor SQL..."
      az sql server create `
        --name $SQL_SERVER_NAME `
        --resource-group $RESOURCE_GROUP `
        --location $LOCATION `
        --admin-user $ADMIN_USER `
        --admin-password $ADMIN_PASSWORD

      Write-Output "Configurando reglas de firewall para permitir acceso..."
      az sql server firewall-rule create `
        --resource-group $RESOURCE_GROUP `
        --server $SQL_SERVER_NAME `
        --name AllowMyIP `
        --start-ip-address 0.0.0.0 `
        --end-ip-address 255.255.255.255

      Write-Output "Creando la base de datos SQL..."
      az sql db create `
        --resource-group $RESOURCE_GROUP `
        --server $SQL_SERVER_NAME `
        --name $DATABASE_NAME `
        --service-objective S0

      Write-Output "Despliegue completado exitosamente."